import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/(components)/footer"
import NavBar from "@/(components)/navBar"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Galeri Alfasarana",
    description: "Generated by create next app",
};

const Links = [
  { id: "L1", name: "Beranda", url: "./index.html" },
  { id: "L2", name: "Kaos", url: "./public/gallery/t-shirts.html" },
  { id: "L3", name: "Tas", url: "./public/gallery/bags.html" },
  { id: "L4", name: "DTF", url: "./public/gallery/dtf.html" },
  { id: "L5", name: "Blog", url: "./public/blogs/main-blog.html" },
  { id: "L6", name: "Kontak", url: "./index.htm#contact-us" },
];

const webLogo = [
  { id: "W1", homepage: "#", bagLogo: "../public/images/website-logo-tas.webp", shirtLogo: "../public/images/website-logo-kaos.webp" },
]

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} dark:bg-gray-900 text-slate-100`}
            >
              <NavBar navLinks={Links} webLogo={webLogo} />
                {children}
            <Footer />
            </body>
        </html>
    );
}
